name: Test Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ] # Trigger workflow on all pushes to main branch

jobs:
  test_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up Python 3.9.0
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: 3.9.0
          architecture: 'x64'

      - name: Run Test Check
        run: |
          cd .github
          python3 test-check.py
